Repository zoobc/zoobc-wallet-web, pull requests merged in 2021-02, with the labels that each got.

#580 [ENHANCEMENT] add GPLv3 license on root
  LICENSE.txt
  src/app/pages/settings/network/network.component.ts
Labels: enhancement, web-wallet

#586 [ENHANCEMENT] Fix potential security vulnerability
  package-lock.json
  package.json
Labels: enhancement

#587 Save fresh network every minutes
  src/app/components/parent/parent.component.ts
Labels: bug, web-wallet

#590 [ENHANCEMENT] Downloadable certificate when waiting etherium transaction
  src/app/components/parent/parent.component.ts
  src/app/pages/seats/waiting-dialog/waiting-dialog.component.html
  src/app/pages/seats/waiting-dialog/waiting-dialog.component.ts
Labels: enhancement
