Repository zoobc/zoobc-wallet-web, pull requests merged in 2021-03, with the labels that each got.

#591 [BUG] Fix cannot match any routes. Url segment angular
  src/app/components/sidebar/sidebar.component.html
  src/app/components/transaction-form/form-escrow-approval/form-escrow-approval.component copy.ts
Labels: bug, web-wallet

#593 [ENHANCEMENT[ Change UI for add new account
  src/app/pages/account/add-account/add-account.component.html
  src/app/pages/account/add-account/add-account.component.ts
  src/app/pages/dashboard/dashboard.component.ts
Labels: enhancement, web-wallet

#594 [ENHANCEMENT] add routerLink to liquid tx icon on dashboard
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/dashboard/dashboard.component.ts
Labels: enhancement

#596 [ENHANCEMENT] show liquid tx when account type is normal
  src/app/pages/dashboard/dashboard.component.html
Labels: enhancement

#599 [ENHANCEMENT] Update main network to be default network
  src/assets/node-list/node-list.json
  src/assets/node-list/node-list.prod.json
Labels: enhancement

#600 [ENHANCEMENT] update announcement
  src/app/components/navbar/navbar.component.html
Labels: enhancement

#604 update node list mainnet and beta
  src/assets/node-list/node-list.json
  src/assets/node-list/node-list.prod.json
Labels: enhancement
